
CREATE TABLE IF NOT EXISTS countries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  iso2 TEXT UNIQUE,
  name TEXT NOT NULL,
  region TEXT,
  subregion TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reactors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  iaea_pris_id TEXT,
  nrc_unit_id TEXT,
  country_id UUID REFERENCES countries(id) ON DELETE SET NULL,
  plant_name TEXT NOT NULL,
  unit_name TEXT,
  reactor_type TEXT,
  status TEXT,
  net_capacity_mwe NUMERIC,
  thermal_power_mwt NUMERIC,
  latitude NUMERIC,
  longitude NUMERIC,
  operator TEXT,
  owner TEXT,
  supplier TEXT,
  construction_start DATE,
  first_grid_connection DATE,
  commercial_operation DATE,
  shutdown_date DATE,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reactors_status ON reactors (status);
CREATE INDEX IF NOT EXISTS idx_reactors_type ON reactors (reactor_type);
CREATE INDEX IF NOT EXISTS idx_reactors_country ON reactors (country_id);

CREATE TABLE IF NOT EXISTS generation_monthly (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reactor_id UUID REFERENCES reactors(id) ON DELETE CASCADE,
  year INT NOT NULL,
  month INT NOT NULL CHECK (month BETWEEN 1 AND 12),
  gross_mwh NUMERIC,
  net_mwh NUMERIC,
  capacity_factor NUMERIC,
  UNIQUE (reactor_id, year, month)
);

CREATE TABLE IF NOT EXISTS country_energy_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id UUID REFERENCES countries(id) ON DELETE CASCADE,
  year INT NOT NULL,
  nuclear_twh NUMERIC,
  total_electricity_twh NUMERIC,
  nuclear_share_percent NUMERIC,
  UNIQUE (country_id, year)
);

CREATE TABLE IF NOT EXISTS reactor_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reactor_id UUID REFERENCES reactors(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  effective_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  reactor_id UUID REFERENCES reactors(id) ON DELETE CASCADE,
  alert_type TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
